---
title: "Goodreads graphs"
author: "Sarah Heidmann"
output: html_document
---

*Data through 31 Dec 2021*
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(tidyverse)
library(lubridate)
library(knitr)
books <- read_csv("data/goodreads_library_export_20211231.csv",
                  col_types = cols(`Date Read`=col_date(format="%Y/%m/%d"),
                                   `Date Added`=col_date(format="%Y/%m/%d")))
# Manually add additional dates for rereads
reread_dates <- tribble(
      ~Index, ~Date,
      1, "2019-01-19", # Dealing w Dragons
      2, "2021-05-15", # Da Vinci Code
      3, "2018-04-15", # Harry 1
      4, "2019-10-03", # Harry 1
      5, "2018-04-15", # Harry 2
      6, "2019-10-04", # Harry 2
      7, "2018-04-19", # Harry 3
      8, "2019-10-04", # Harry 3
      9, "2018-04-25", # Harry 4
      10, "2019-10-08", # Harry 4
      11, "2018-05-03", # Harry 5
      12, "2019-10-15", # Harry 5
      13, "2018-05-06", # Harry 6
      14, "2019-10-19", # Harry 6
      15, "2018-05-08", # Harry 7
      16, "2019-10-26", # Harry 7
      17, "2020-08-21", # Eragon
      18, "2021-01-28", # Dune
      19, NA, # Ender's Game 
      20, "2017-05-20", # Little Prince
      21, "2020-12-21", # Little Prince
      22, NA, # Hobbit
      23, NA, # Fahrenheit 451
      24, NA, # Night
      25, "2021-08-12", # Wrinkle in Time
      26, "2018-05-26", # Sun and Her Flowers
      27, "2019-08-21", # Sun and Her Flowers
      28, NA, # Brave New World
      29, "2020-12-02", # Brave New World
      30, "2019-07-06", # Fifth Season
      31, NA, # Once Upon a Marigold
      32, NA, # House of the Scorpion
      33, "2021-12-05", # Eye of World
      34, "2020-07-30", # AART
      35, "2021-01-29", # Murderbot
      36, NA, # Giver
      37, NA, # Animal Farm
      38, NA # Sherlock 3
) %>%
      mutate(Date = date(Date))
rereads <- books %>% 
      filter(`Read Count` > 1) %>%
      arrange(`Date Read`) %>%
      uncount(`Read Count`-1) %>% # Must subtract 1 so merging doesn't duplicate
      mutate(`Date Read`=replace(`Date Read`,
                                 reread_dates$Index, reread_dates$Date)) %>%
      bind_rows(books)
```

## Goodreads redone
### Books and pages read each year

```{r BooksAndPagesYear}
minYear <- year(min(books$`Date Read`, na.rm = TRUE))
maxYear <- year(max(books$`Date Read`, na.rm = TRUE))

# Books per year
rereads %>%
      filter(!is.na(`Date Read`)) %>%
      mutate(YearRead = year(`Date Read`)) %>%
      ggplot(data=.) +
      geom_histogram(aes(x=YearRead), binwidth=1,
                     fill= "turquoise", color = "blue") +
      scale_y_continuous(name="Number of Books Read", expand = c(0,0)) +
      scale_x_continuous(name= "",
                         breaks = seq(minYear,maxYear,1),
                         labels = seq(minYear,maxYear,1)) +
      theme(panel.background = element_blank(),
            axis.line = element_line())

# Pages per year
rereads %>%
      filter(!is.na(`Date Read`)) %>%
      mutate(YearRead = year(`Date Read`)) %>%
      ggplot(data=.) +
      geom_bar(aes(x=YearRead, y=`Number of Pages`), stat="identity",
                     fill= "turquoise", color = "blue") +
      scale_y_continuous(name="Number of Pages Read", expand = c(0,0)) +
      scale_x_continuous(name= "",
                         breaks = seq(minYear,maxYear,1),
                         labels = seq(minYear,maxYear,1)) +
      theme(panel.background = element_blank(),
            axis.line = element_line())
```

### Publication year by date read

```{r PubYear}
# I have a couple outliers, so set a minimum publication date
earliestPub <- 1800

rereads %>%
      filter(!is.na(`Date Read`)) %>%
      ggplot(data=.) +
      geom_point(aes(x=`Date Read`, y=`Original Publication Year`),
                 color = "blue") +
      scale_y_continuous(name="Publication Date", expand = c(0,0),
                         limits = c(earliestPub, maxYear)) +
      theme(panel.background = element_blank(),
            axis.line = element_line())
```

### Books and pages read each month

```{r BooksAndPagesMonth}
# Books by month
rereads %>%
      filter(!is.na(`Date Read`)) %>%
      mutate(MonthRead = floor_date(`Date Read`, "month")) %>%
      group_by(MonthRead) %>%
      summarize(BooksRead = length(Title),
                .groups="drop") %>%
      ggplot(data=.) +
      geom_bar(aes(x=MonthRead, y=BooksRead), stat="identity",
                     fill= "turquoise", color = "blue") +
      scale_y_continuous(name="Number of Books Read", expand = c(0,0),
                         breaks = seq(0,35,5), limits = c(0,35)) +
      scale_x_date(date_breaks="1 month", date_labels="%Y-%b", expand=c(0,0)) +
      theme(panel.background = element_blank(),
            axis.line = element_line(),
            axis.text.x =element_text(angle=-90))

# Pages by month
rereads %>%
      filter(!is.na(`Date Read`)) %>%
      mutate(MonthRead = floor_date(`Date Read`, "month")) %>%
      group_by(MonthRead) %>%
      summarize(PagesRead = sum(`Number of Pages`, na.rm = TRUE),
                .groups="drop") %>%
      ggplot(data=.) +
      geom_bar(aes(x=MonthRead, y=PagesRead), stat="identity",
               fill= "turquoise", color = "blue") +
      scale_y_continuous(name="Number of Pages Read", expand = c(0,0),
                         breaks = seq(0,10000,2500), limits = c(0,12000)) +
      scale_x_date(date_breaks="1 month", date_labels="%Y-%b", expand=c(0,0)) +
      theme(panel.background = element_blank(),
            axis.line = element_line(),
            axis.text.x =element_text(angle=-90))
```

## My extras
### Most read books
```{r MostRead}
# For now it is all books I have read more than once
# Eventually I want it to be my top 10
# Although maybe that's too boring since 7 will be Harry Potter
books %>%
      arrange(desc(`Read Count`)) %>%
      select(Title, `Read Count`) %>%
      filter(`Read Count` >1) %>%
      ggplot(data=.) +
      geom_bar(aes(x=reorder(Title, -`Read Count`), y=`Read Count`), 
               stat="identity",
               fill= "turquoise", color = "blue") +
      scale_y_continuous(name="Number of Times Read", expand = c(0,0)) +
      theme(panel.background = element_blank(),
            axis.line = element_line(),
            axis.text.x =element_text(angle=-80, hjust=0.05),
            axis.title.x = element_blank())
```

### Books added/read by month
```{r AddRead}
# I added much of my library in the first few days of using Goodreads.
# Set a date limit to exclude those outlier days
books %>%
   mutate(MonthAdded=floor_date(`Date Added`,"month"),
          MonthRead=floor_date(`Date Read`,"month")) %>%
   ggplot(data=.) +
      geom_bar(aes(x=MonthAdded,y=..count..), fill = NA,
                     color = "blue") +
      geom_bar(aes(x=MonthRead,y=..count..), fill = NA,
                     color = "green") +
      scale_y_continuous(name ="",expand = c(0,0)) +
      scale_x_date(date_breaks = "1 month", date_labels = "%Y-%b",
                   limits = c(ymd("2014-03-01"),NA), expand=c(0,0)) +
      theme(panel.background = element_blank(),
            axis.line = element_line(),
            axis.text.x =element_text(angle=-90))
```

### Rate added/read by month
```{r AddReadRate}
addDates <- books %>% 
   mutate(Month = floor_date(`Date Added`, "month")) %>%
   group_by(Month) %>% 
   summarize(BooksAdded=length(Month), .groups="drop")
readDates <- books %>% 
   filter(!is.na(`Date Read`)) %>%
   mutate(Month = floor_date(`Date Read`, "month")) %>%
   group_by(Month) %>% 
   summarize(BooksRead=length(Month), .groups="drop")
add_read <- full_join(addDates, readDates, by= "Month") %>% 
   replace_na(list(BooksAdded = 0, BooksRead = 0)) %>%
   mutate(diff = BooksAdded - BooksRead)
   
ggplot(data=add_read)+
   geom_line(aes(x=Month,y=diff)) +
   scale_y_continuous(name="Net Books",limits = c(-20,50)) +
   scale_x_date(date_breaks = "1 month", date_labels = "%Y-%b",
                limits = c(ymd("2014-03-01"),NA), expand=c(0,0)) +
   geom_hline(yintercept=0, color = "blue") +
   theme(panel.background=element_blank(),
         axis.line = element_line(),
         axis.text.x=element_text(angle=-90),
         axis.title.x=element_blank())
```

### Cumulative want-to-read
```{r CumWTR}
wtr <- add_read %>%
   # Take out the first two months when I added my to-read list
   arrange(Month) %>% slice(-1:-2) %>% 
   mutate(cumdiff=cumsum(diff))
# Use saved tibble to access max y-value
ggplot(data=wtr)+
   geom_line(aes(x=Month,y=cumdiff)) +
   scale_y_continuous(name="Want to Read") +
   scale_x_date(date_breaks = "1 month", date_labels = "%Y-%b", expand=c(0,0)) +
   geom_hline(yintercept=max(wtr$cumdiff), color="blue") +
   theme(panel.background=element_blank(),
         axis.line = element_line(),
         axis.text.x=element_text(angle=-90),
         axis.title.x=element_blank())
```

### Ratio of want-to-read to read over time
```{r ratioWTR}
ratiowtr <- wtr %>%
      mutate(cumAdded = cumsum(BooksAdded),
             cumRead = cumsum(BooksRead)) %>%
      mutate(ratio = (cumAdded - cumRead)/cumRead)

ggplot(data=ratiowtr)+
   geom_line(aes(x=Month,y=ratio)) +
   scale_y_continuous(name="Ratio of Want-to-Read to Read") +
   scale_x_date(date_breaks = "1 month", date_labels = "%Y-%b", expand=c(0,0)) +
   theme(panel.background=element_blank(),
         axis.line = element_line(),
         axis.text.x=element_text(angle=-90),
         axis.title.x=element_blank())
```

### How long is a book on my shelf before reading it?
```{r TimeWTR}
# Histogram view
books %>%
   filter(!is.na(`Date Read`)) %>%
   mutate(daysonlist = as.numeric(`Date Read` - `Date Added`)) %>%
   filter(daysonlist>0) %>%
   ggplot(data=.) +
   geom_histogram(aes(x=daysonlist), binwidth=100,
                  color = "blue",fill="turquoise") +
   xlab("Days on Want to Read") + ylab("") +
   scale_y_continuous(expand=c(0,0))+
   theme(panel.background=element_blank(),
         axis.line= element_line())
```

### Average books read by month
```{r BooksMonth}
rereads %>%
      filter(!is.na(`Date Read`)) %>%
      mutate(MonthYear = floor_date(`Date Read`, "month"),
             Month = month(MonthYear, label = TRUE, abbr = TRUE)) %>%
      group_by(MonthYear, Month) %>%
      summarize(sumBooks = length(Title), 
                .groups="drop") %>%
      group_by(Month) %>%
      summarize(meanBooks = mean(sumBooks), 
                nMonths = length(sumBooks),
                seBooks = sd(sumBooks)/sqrt(length(sumBooks)),
                .groups="drop") %>%
      ggplot(data=.) +
      geom_bar(aes(x=Month, y=meanBooks), stat="identity",
                     fill= "turquoise", color = "blue") +
      geom_errorbar(aes(x=Month, 
                        ymax=meanBooks+seBooks, ymin=meanBooks-seBooks),
                    color = "blue", width = 0.25) +
      scale_y_continuous(name="Number of Books Read", expand = c(0,0)) +
      theme(panel.background = element_blank(),
            axis.line = element_line())
```

